---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/clients/{client_id}/transactions":
    get:
      summary: transactions client
      parameters:
      - name: client_id
        in: path
        description: client_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example_0:
                  value:
                  - id: 1
                    source_currency: USD
                    target_currency: BTC
                    source_amount: 123.12345
                    target_amount: 567.64334123
                    client_id: 1
                    exchange_rate: 123.0
        '404':
          description: Not found
          content:
            application/json:
              examples:
                example_0:
                  value:
                    error: Client doesn't exist or invalid client.
  "/api/v1/clients":
    post:
      summary: create client
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                example_0:
                  value:
                    message: Successfully created the client.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              examples:
                example_0:
                  value:
                    error:
                    - Username can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
        description: Client object containing username
  "/api/v1/exchange_rates":
    get:
      summary: Retrieve exchange rate
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example_0:
                  value:
                    USD:
                      code: USD
                      symbol: "&#36;"
                      rate: '64,383.614'
                      description: United States Dollar
                      rate_float: 64383.6143
                    GBP:
                      code: GBP
                      symbol: "&pound;"
                      rate: '50,882.048'
                      description: British Pound Sterling
                      rate_float: 50882.0484
                    EUR:
                      code: EUR
                      symbol: "&euro;"
                      rate: '60,213.81'
                      description: Euro
                      rate_float: 60213.8095
        '503':
          description: Service Unavailable
          content:
            application/json:
              examples:
                example_0:
                  value:
                    error: CoinDesk API is currently unavailable
servers:
- url: https://vitaexercise.onrender.com
  variables:
    defaultHost:
      default: vitaexercise.onrender.com
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
